CREATE TABLE signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    repo_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,

    user_id UUID REFERENCES users(id) ON DELETE SET NULL,

    -- ci_failure | github_issue | log
    type TEXT NOT NULL,

    -- GitHub issue number, workflow/run ID, etc.
    source_ref TEXT,

    raw_content TEXT NOT NULL,

    parsed_stack_trace JSONB,
    parsed_data JSONB,

    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX signals_repo_id_idx
    ON signals(repo_id);

CREATE INDEX signals_type_idx
    ON signals(type);


CREATE TABLE fix_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    repo_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,

    signal_id UUID NOT NULL REFERENCES signals(id) ON DELETE CASCADE,

    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN (
            'queued',
            'reindexing',
            'analyzing_signal',
            'localizing',
            'root_cause',
            'generating',
            'validating',
            'awaiting_approval',
            'pr_created',
            'failed'
        )),

    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0 AND attempt_count <= 3),

    approved_at TIMESTAMP,

    approved_by UUID REFERENCES users(id) ON DELETE SET NULL,

    error_message TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX fix_jobs_repo_id_idx
    ON fix_jobs(repo_id);

CREATE INDEX fix_jobs_signal_id_idx
    ON fix_jobs(signal_id);

CREATE INDEX fix_jobs_status_idx
    ON fix_jobs(status);


CREATE TABLE job_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    job_id UUID NOT NULL REFERENCES fix_jobs(id) ON DELETE CASCADE,

    stage TEXT NOT NULL,
    message TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX job_events_job_id_idx
    ON job_events(job_id);

CREATE INDEX job_events_job_created_idx
    ON job_events(job_id, created_at);


CREATE TABLE localization_candidates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    job_id UUID NOT NULL REFERENCES fix_jobs(id) ON DELETE CASCADE,

    chunk_id UUID NOT NULL REFERENCES code_chunks(id) ON DELETE CASCADE,

    rank INTEGER NOT NULL,
    score DOUBLE PRECISION,

    -- stack_trace_direct | embedding
    method TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT now(),

    UNIQUE (job_id, chunk_id)
);

CREATE INDEX localization_candidates_job_idx
    ON localization_candidates(job_id);

CREATE INDEX localization_candidates_rank_idx
    ON localization_candidates(job_id, rank);


CREATE TABLE patches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    job_id UUID NOT NULL REFERENCES fix_jobs(id) ON DELETE CASCADE,

    attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1 AND attempt_number <= 3),

    -- Unified diff generated by Fix Generation Agent
    diff_content TEXT NOT NULL,

    explanation TEXT,

    validation_passed BOOLEAN,
    validation_log TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT now(),

    UNIQUE (job_id, attempt_number)
);

CREATE INDEX patches_job_id_idx
    ON patches(job_id);


CREATE TABLE pull_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    job_id UUID NOT NULL REFERENCES fix_jobs(id) ON DELETE CASCADE,

    patch_id UUID NOT NULL REFERENCES patches(id) ON DELETE RESTRICT,

    pr_number INTEGER,
    pr_url TEXT,

    status TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN (
            'open',
            'closed',
            'merged'
        )),

    created_at TIMESTAMP NOT NULL DEFAULT now(),

    UNIQUE (job_id)
);

CREATE INDEX pull_requests_job_id_idx
    ON pull_requests(job_id);